builds:
  - ldflags:
      - -X main.version={{.Version}} -X main.commit={{.Commit}} -s -w
    main: ./cmd/root/main.go
    goarch:
      - amd64
      - arm
      - arm64
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarm:
      - 6
      - 7
dockers:
- image_templates:
  - "sudermanjr/riley:{{ .Tag }}-linux-amd64"
  - "sudermanjr/riley:v{{ .Major }}-linux-amd64"
  - "sudermanjr/riley:v{{ .Major }}.{{ .Minor }}-linux-amd64"
  use: buildx
  dockerfile: Dockerfile
  goarch: amd64
  goos: linux
  build_flag_templates:
  - "--platform=linux/amd64"
- image_templates:
  - "sudermanjr/riley:{{ .Tag }}-linux-arm64v8"
  - "sudermanjr/riley:v{{ .Major }}-linux-arm64v8"
  - "sudermanjr/riley:v{{ .Major }}.{{ .Minor }}-linux-arm64v8"
  use: buildx
  goarch: arm64
  goos: linux
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/arm64/v8"
- image_templates:
  - "sudermanjr/riley:{{ .Tag }}-linux-armv7"
  - "sudermanjr/riley:v{{ .Major }}-linux-armv7"
  - "sudermanjr/riley:v{{ .Major }}.{{ .Minor }}-linux-armv7"
  use: buildx
  goarch: arm64
  goos: linux
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/arm/v7"
docker_manifests:
- name_template: sudermanjr/riley:{{ .Tag }}
  image_templates:
  - "sudermanjr/riley:{{ .Tag }}-linux-amd64"
  - "sudermanjr/riley:{{ .Tag }}-linux-arm64v8"
  - "sudermanjr/riley:{{ .Tag }}-linux-armv7"
- name_template: sudermanjr/riley:v{{ .Major }}
  image_templates:
  - "sudermanjr/riley:v{{ .Major }}-linux-amd64"
  - "sudermanjr/riley:v{{ .Major }}-linux-arm64v8"
  - "sudermanjr/riley:v{{ .Major }}-linux-armv7"
- name_template: sudermanjr/riley:v{{ .Major }}.{{ .Minor }}
  image_templates:
  - "sudermanjr/riley:v{{ .Major }}.{{ .Minor }}-linux-amd64"
  - "sudermanjr/riley:v{{ .Major }}.{{ .Minor }}-linux-arm64v8"
  - "sudermanjr/riley:v{{ .Major }}.{{ .Minor }}-linux-armv7"
